### PR TITLE
docs: Added OCI Push to usecases

### PR DESCRIPTION
**Pull request by ashokdevtron**

### CODE REVIEW

**Review by abhibhaw — CHANGES_REQUESTED** [review]
Is Enterprise flag missing here @ashokdevtron ?

**Review by abhibhaw — CHANGES_REQUESTED** [review]
We sould also have an usecase section (must for this doc)

**Review by uxarya-d — CHANGES_REQUESTED** [review]
We should put a detailed coverage of the use case this feature is solving in the Use cases section with link to this page.
This page should also start(suggestion) with the use case(could be a trimmed down version of the content for the use case page with a link to the page), followed by the steps to achieve it.

**Comment by ashokdevtron** [comment]
Closing this PR, because it had to be written differently as per Utkarsh's review. Will rewrite it again.

**Pull request closed without merging**
