### PR TITLE
doc: fixed broken link and improved documentation in usecases

### PR DESCRIPTION
**Pull request by CharithaCS**
Fixed broken links and improved documentation

# Description

Fixes #
### 1. Fixed broken link:  
**Connect Django with MySql database** resulted in a 404 error when clicked. This has been fixed now. 2023-10-14 10_31_24-Use Cases - Devtron and 14 more pages - Personal - Microsoft​ Edge
2023-10-14 10_31_39-File not found and 15 more pages - Personal - Microsoft​ Edge

## How Has This Been Tested?
- [x] The link when clicked should redirect to the intended webpage

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] Does this PR requires documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by ashokdevtron — APPROVED** [review]

**Comment by CharithaCS** [comment]
@ashokdevtron, could you please help me on why the workflow failed and what I need to do to resolve this?

**Comment by ashokdevtron** [comment]
> @ashokdevtron, could you please help me on why the workflow failed and what I need to do to resolve this?

@CharithaCS, yes, there's an issue from our end and we are looking into it.

**Comment by CharithaCS** [comment]
> > @ashokdevtron, could you please help me on why the workflow failed and what I need to do to resolve this?
> 
> @CharithaCS, yes, there's an issue from our end and we are looking into it.

Oh Alright!

**Review by prakarsh-dt — DISMISSED** [review]

**Comment by CharithaCS** [comment]
Hello maintainers! May I know why the workflow failed? I'd like to resolve the issue which is preventing this PR from getting merged.

**Comment by pawan-mehta-dt** [comment]
Hi @CharithaCS please sync your fork with devtron main branch or else it'll revert a lot of changes on devtron main

**Comment by ashokdevtron** [comment]
@CharithaCS, it seems your PR also contains few changes other than documentation. It could be because of merging some other branch with your branch. Ideally, the scope of your PR should remain restricted to documentation-related files only, can you revert other commits you might have pulled?

**Comment by CharithaCS** [comment]
> Hi @CharithaCS please sync your fork with devtron main branch or else it'll revert a lot of changes on devtron main

I've synced the fork. Please review the changes

**Pull request merged**
